dist: bionic
language: minimal
arch:
  - ppc64le
  - amd64
env:
  - BUILD_TYPE=Release USE_NVML=ON
  - BUILD_TYPE=Debug   USE_NVML=ON
  - BUILD_TYPE=Release USE_NVML=OFF
  - BUILD_TYPE=Debug   USE_NVML=OFF


cache:
  directories:
    $HOME/cmake

install:
  - ci/install_deps.sh || travis_terminate 1;

script:
  - ci/build.sh || travis_terminate 1;
  - ci/test.sh || travis_terminate 1;
